#pragma warning disable 1591
namespace ILNumerics_Licensing {
    /// <summary>
    /// This type supports ILNumerics infrastructure. Do not edit the code!
    /// </summary>
    /// <remarks>This type is automatically generated by ILNumerics Ultimate VS. If you encounter problems compiling this file, make sure to reference ILNumerics.Core in your project!</remarks>
    [System.ComponentModel.LicenseProvider(typeof(ILNumerics.Licensing.ILLicenseProvider))]  // <- ILNumerics.Core is needed here!
    public partial class ILLicHelper_78afeccce1444593b5fd496822f46654_ { public ILLicHelper_78afeccce1444593b5fd496822f46654_() { System.ComponentModel.LicenseManager.Validate(typeof(ILLicHelper_78afeccce1444593b5fd496822f46654_), this); } }
}